import { ClozeExerciseItem } from '../../src/types/ai';

export const minna14Exercises: ClozeExerciseItem[] = [
  {
    id: 'cloze_minna_14_0',
    vocabId: 'minna_14_0',
    targetWord: 'つけます',
    targetReading: 'つけます',
    sentence: '部屋が暗いですから、電気を（　　）てください。',
    fullSentence: '部屋が暗いですから、電気をつけてください。',
    translation: 'Vì phòng tối nên xin hãy bật đèn lên.',
    options: ['つけ', '消し', '開け', '閉め'],
    correctIndex: 0,
    explanation: '「つけます」 nghĩa là bật (thiết bị điện tử, đèn điện, máy lạnh).'
  },
  {
    id: 'cloze_minna_14_1',
    vocabId: 'minna_14_1',
    targetWord: '消します',
    targetReading: 'けします',
    sentence: '出かける前に、エアコンを（　　）てください。',
    fullSentence: '出かける前に、エアコンを消してください。',
    translation: 'Trước khi đi ra ngoài, xin hãy tắt máy điều hòa.',
    options: ['消し', 'つけ', '閉め', '開け'],
    correctIndex: 0,
    explanation: '「消します」（けします） nghĩa là tắt (thiết bị điện, dập lửa).'
  },
  {
    id: 'cloze_minna_14_2',
    vocabId: 'minna_14_2',
    targetWord: '開けます',
    targetReading: 'あけます',
    sentence: '部屋が暑いですから、窓を（　　）てください。',
    fullSentence: '部屋が暑いですから、窓を開けてください。',
    translation: 'Vì trong phòng nóng nực nên xin hãy mở cửa sổ ra.',
    options: ['開け', '閉め', 'つけ', '消し'],
    correctIndex: 0,
    explanation: '「開けます」（あけます） nghĩa là mở (cửa ra vào, cửa sổ, nắp hộp).'
  },
  {
    id: 'cloze_minna_14_3',
    vocabId: 'minna_14_3',
    targetWord: '閉めます',
    targetReading: 'しめます',
    sentence: '雨が降っていますから、ドアを（　　）てください。',
    fullSentence: '雨が降っていますから、ドアを閉めてください。',
    translation: 'Trời đang mưa nên xin hãy đóng cửa lại.',
    options: ['閉め', '開け', 'つけ', '止め'],
    correctIndex: 0,
    explanation: '「閉めます」（しめます） nghĩa là đóng (cửa).'
  },
  {
    id: 'cloze_minna_14_4',
    vocabId: 'minna_14_4',
    targetWord: '急ぎます',
    targetReading: 'いそぎます',
    sentence: '時間がありませんから、（　　）ましょう。',
    fullSentence: '時間がありませんから、急ぎましょう。',
    translation: 'Vì không còn thời gian nữa nên chúng ta hãy nhanh chóng / khẩn trương lên nào.',
    options: ['急ぎ', '待ち', '休み', '話'],
    correctIndex: 0,
    explanation: '「急ぎます」（いそぎます） nghĩa là gấp rút, khẩn trương, vội vã.'
  },
  {
    id: 'cloze_minna_14_5',
    vocabId: 'minna_14_5',
    targetWord: '待ちます',
    targetReading: 'まちます',
    sentence: '駅の前で友達を（　　）ています。',
    fullSentence: '駅の前で友達を待っています。',
    translation: 'Tôi đang đứng chờ bạn ở phía trước nhà ga.',
    options: ['待っ', '呼ん', '話し', '取っ'],
    correctIndex: 0,
    explanation: '「待ちます」（まちます） chia thể て là 「待っています」 nghĩa là đang chờ đợi.'
  },
  {
    id: 'cloze_minna_14_6',
    vocabId: 'minna_14_6',
    targetWord: '止めます',
    targetReading: 'とめます',
    sentence: 'あそこに車を（　　）てください。',
    fullSentence: 'あそこに車を止めてください。',
    translation: 'Xin hãy dừng / đỗ xe ở đằng kia.',
    options: ['止め', '閉め', '見せ', 'つけ'],
    correctIndex: 0,
    explanation: '「止めます」（とめます） nghĩa là dừng lại, đỗ xe.'
  },
  {
    id: 'cloze_minna_14_7',
    vocabId: 'minna_14_7',
    targetWord: '曲がります',
    targetReading: 'まがります',
    sentence: '次の角を右へ（　　）てください。',
    fullSentence: '次の角を右へ曲がってください。',
    translation: 'Xin hãy rẽ phải ở góc đường tiếp theo.',
    options: ['曲がっ', '止まっ', '行っ', '渡っ'],
    correctIndex: 0,
    explanation: '「曲がります」（まがります） đi với hướng + へ nghĩa là rẽ / quẹo.'
  },
  {
    id: 'cloze_minna_14_8',
    vocabId: 'minna_14_8',
    targetWord: '持ちます',
    targetReading: 'もちます',
    sentence: '重い荷物を（　　）ましょうか。',
    fullSentence: '重い荷物を持ちましょうか。',
    translation: 'Tôi xách / mang giúp bạn hành lý nặng nhé?',
    options: ['持ち', '取り', '開け', '貸し'],
    correctIndex: 0,
    explanation: '「持ちます」（もちます） nghĩa là cầm, nắm, mang xách.'
  },
  {
    id: 'cloze_minna_14_9',
    vocabId: 'minna_14_9',
    targetWord: '取ります',
    targetReading: 'とります',
    sentence: 'すみませんが、そこの塩を（　　）てください。',
    fullSentence: 'すみませんが、そこの塩を取ってください。',
    translation: 'Xin lỗi, làm ơn lấy giúp tôi lọ muối ở đằng đó với.',
    options: ['取っ', '持っ', '見せ', '教え'],
    correctIndex: 0,
    explanation: '「取ります」（とります） nghĩa là lấy, với lấy đồ vật giúp ai đó.'
  },
  {
    id: 'cloze_minna_14_10',
    vocabId: 'minna_14_10',
    targetWord: '手伝います',
    targetReading: 'てつだいます',
    sentence: '母の料理を（　　）ました。',
    fullSentence: '母の料理を手伝いました。',
    translation: 'Tôi đã phụ giúp mẹ nấu ăn.',
    options: ['手伝い', '教え', '見せ', '呼び'],
    correctIndex: 0,
    explanation: '「手伝います」（てつだいます） nghĩa là giúp đỡ, phụ việc.'
  },
  {
    id: 'cloze_minna_14_11',
    vocabId: 'minna_14_11',
    targetWord: '呼びます',
    targetReading: 'よびます',
    sentence: '雨が降っていますから、タクシーを（　　）ましょう。',
    fullSentence: '雨が降っていますから、タクシーを呼びましょう。',
    translation: 'Trời đang mưa nên chúng ta hãy gọi xe taxi nhé.',
    options: ['呼び', '待ち', '止め', '降り'],
    correctIndex: 0,
    explanation: '「呼びます」（よびます） nghĩa là gọi (người hoặc phương tiện xe cộ).'
  },
  {
    id: 'cloze_minna_14_12',
    vocabId: 'minna_14_12',
    targetWord: '話します',
    targetReading: 'はなします',
    sentence: '先生と日本語で（　　）ました。',
    fullSentence: '先生と日本語で話しました。',
    translation: 'Tôi đã trò chuyện bằng tiếng Nhật với thầy giáo.',
    options: ['話し', '聞き', '呼び', '待ち'],
    correctIndex: 0,
    explanation: '「話します」（はなします） nghĩa là nói chuyện, trao đổi.'
  },
  {
    id: 'cloze_minna_14_13',
    vocabId: 'minna_14_13',
    targetWord: '見せます',
    targetReading: 'みせます',
    sentence: 'パスポートを（　　）てください。',
    fullSentence: 'パスポートを見せてください。',
    translation: 'Xin vui lòng cho tôi xem hộ chiếu.',
    options: ['見せ', '見', '取っ', '教え'],
    correctIndex: 0,
    explanation: '「見せます」（みせます） nghĩa là cho ai đó xem cái gì.'
  },
  {
    id: 'cloze_minna_14_14',
    vocabId: 'minna_14_14',
    targetWord: '教えます',
    targetReading: 'おしえます',
    sentence: 'あなたの住所と電話番号を（　　）てください。',
    fullSentence: 'あなたの住所と電話番号を教えてください。',
    translation: 'Xin hãy cho tôi biết địa chỉ và số điện thoại của bạn.',
    options: ['教え', '見せ', '話し', '取り'],
    correctIndex: 0,
    explanation: '「教えます」（おしえます） nghĩa là chỉ cho biết, bảo cho biết thông tin.'
  },
  {
    id: 'cloze_minna_14_15',
    vocabId: 'minna_14_15',
    targetWord: '始めます',
    targetReading: 'はじめます',
    sentence: 'では、今日の授業を（　　）ましょう。',
    fullSentence: 'では、今日の授業を始めましょう。',
    translation: 'Nào, chúng ta bắt đầu bài học hôm nay nhé.',
    options: ['始め', '終わり', '止め', '休み'],
    correctIndex: 0,
    explanation: '「始めます」（はじめます） nghĩa là bắt đầu tiến hành công việc hoặc tiết học.'
  },
  {
    id: 'cloze_minna_14_16',
    vocabId: 'minna_14_16',
    targetWord: '降ります',
    targetReading: 'ふります',
    sentence: '外で雨が（　　）ています。',
    fullSentence: '外で雨が降っています。',
    translation: 'Ở bên ngoài trời đang đổ mưa.',
    options: ['降っ', '止ん', '呼ん', '待っ'],
    correctIndex: 0,
    explanation: '「雨が降ります」（ふります） chia thể て là 「降っています」 nghĩa là mưa đang rơi.'
  },
  {
    id: 'cloze_minna_14_17',
    vocabId: 'minna_14_17',
    targetWord: 'コピーします',
    targetReading: 'コピーします',
    sentence: 'この資料を10枚（　　）てください。',
    fullSentence: 'この資料を10枚コピーしてください。',
    translation: 'Xin vui lòng photo / in sao chép 10 bản tài liệu này.',
    options: ['コピーし', '見せ', '教え', '書き'],
    correctIndex: 0,
    explanation: '「コピーします」 nghĩa là photocopy, sao chép văn bản.'
  },
  {
    id: 'cloze_minna_14_18',
    vocabId: 'minna_14_18',
    targetWord: 'エアコン',
    targetReading: 'エアコン',
    sentence: '部屋が暑いですから、（　　）をつけてください。',
    fullSentence: '部屋が暑いですから、エアコンをつけてください。',
    translation: 'Phòng nóng quá nên xin hãy bật máy điều hòa lên.',
    options: ['エアコン', 'パスポート', '地図', '砂糖'],
    correctIndex: 0,
    explanation: '「エアコン」 nghĩa là máy điều hòa nhiệt độ không khí.'
  },
  {
    id: 'cloze_minna_14_19',
    vocabId: 'minna_14_19',
    targetWord: 'パスポート',
    targetReading: 'パスポート',
    sentence: '空港で（　　）を見せました。',
    fullSentence: '空港でパスポートを見せました。',
    translation: 'Tôi đã xuất trình hộ chiếu ở sân bay.',
    options: ['パスポート', 'エアコン', '地図', '塩'],
    correctIndex: 0,
    explanation: '「パスポート」 nghĩa là quyển hộ chiếu xuất nhập cảnh.'
  },
  {
    id: 'cloze_minna_14_20',
    vocabId: 'minna_14_20',
    targetWord: '名前',
    targetReading: 'なまえ',
    sentence: 'ここにあなたの（　　）を漢字で書いてください。',
    fullSentence: 'ここにあなたの名前を漢字で書いてください。',
    translation: 'Xin hãy viết họ tên của bạn bằng chữ Hán vào đây.',
    options: ['名前', '住所', '地図', '砂糖'],
    correctIndex: 0,
    explanation: '「名前」（なまえ） nghĩa là họ và tên.'
  },
  {
    id: 'cloze_minna_14_21',
    vocabId: 'minna_14_21',
    targetWord: '住所',
    targetReading: 'じゅうしょ',
    sentence: '荷物を送りたいですから、（　　）を教えてください。',
    fullSentence: '荷物を送りたいですから、住所を教えてください。',
    translation: 'Vì muốn gửi bưu phẩm nên xin bạn hãy cho tôi biết địa chỉ.',
    options: ['住所', '名前', 'パスポート', '塩'],
    correctIndex: 0,
    explanation: '「住所」（じゅうしょ） nghĩa là địa chỉ nhà ở.'
  },
  {
    id: 'cloze_minna_14_22',
    vocabId: 'minna_14_22',
    targetWord: '地図',
    targetReading: 'ちず',
    sentence: '道がわかりませんから、（　　）を見ます。',
    fullSentence: '道がわかりませんから、地図を見ます。',
    translation: 'Vì không biết đường nên tôi xem bản đồ.',
    options: ['地図', '住所', '名前', '切手'],
    correctIndex: 0,
    explanation: '「地図」（ちず） nghĩa là bản đồ địa lý.'
  },
  {
    id: 'cloze_minna_14_23',
    vocabId: 'minna_14_23',
    targetWord: '塩',
    targetReading: 'しお',
    sentence: 'スープの味が薄いですから、（　　）を少し入れます。',
    fullSentence: 'スープの味が薄いですから、塩を少し入れます。',
    translation: 'Vị canh hơi nhạt nên tôi cho thêm một chút muối.',
    options: ['塩', '砂糖', '地図', '名前'],
    correctIndex: 0,
    explanation: '「塩」（しお） nghĩa là muối ăn.'
  },
  {
    id: 'cloze_minna_14_24',
    vocabId: 'minna_14_24',
    targetWord: '砂糖',
    targetReading: 'さとう',
    sentence: '甘いコーヒーが好きですから、（　　）を入れます。',
    fullSentence: '甘いコーヒーが好きですから、砂糖を入れます。',
    translation: 'Vì thích cà phê ngọt nên tôi cho đường vào.',
    options: ['砂糖', '塩', '地図', 'エアコン'],
    correctIndex: 0,
    explanation: '「砂糖」（さとう） nghĩa là đường cát, đường ăn.'
  },
  {
    id: 'cloze_minna_14_25',
    vocabId: 'minna_14_25',
    targetWord: '読み方',
    targetReading: 'よみかた',
    sentence: 'この漢字の（　　）を教えてください。',
    fullSentence: 'この漢字の読み方を教えてください。',
    translation: 'Xin hãy chỉ cho tôi cách đọc của chữ Hán này.',
    options: ['読み方', '作り方', '使い方', '行き方'],
    correctIndex: 0,
    explanation: '「読み方」（よみかた） nghĩa là cách đọc một chữ hoặc từ vựng.'
  },
  {
    id: 'cloze_minna_14_26',
    vocabId: 'minna_14_26',
    targetWord: '方',
    targetReading: 'かた',
    sentence: 'このパソコンの使い（　　）がわかりません。',
    fullSentence: 'このパソコンの使い方がわかりません。',
    translation: 'Tôi không biết cách sử dụng chiếc máy vi tính này.',
    options: ['方', '人', '物', '間'],
    correctIndex: 0,
    explanation: 'Động từ thể ます bỏ ます + 「方」（かた） tạo thành danh từ chỉ cách thức thực hiện hành động (như 使い方: cách dùng).'
  },
  {
    id: 'cloze_minna_14_27',
    vocabId: 'minna_14_27',
    targetWord: 'ゆっくり',
    targetReading: 'ゆっくり',
    sentence: 'もう少し（　　）話してください。聞き取れませんでした。',
    fullSentence: 'もう少しゆっくり話してください。聞き取れませんでした。',
    translation: 'Xin hãy nói chậm rãi hơn một chút. Tôi đã chưa nghe kịp.',
    options: ['ゆっくり', 'すぐ', 'また', 'あとで'],
    correctIndex: 0,
    explanation: '「ゆっくり」 nghĩa là từ từ, chậm rãi, thong thả.'
  },
  {
    id: 'cloze_minna_14_28',
    vocabId: 'minna_14_28',
    targetWord: 'すぐ',
    targetReading: 'すぐ',
    sentence: '危ないですから、（　　）戻ってください。',
    fullSentence: '危ないですから、すぐ戻ってください。',
    translation: 'Nguy hiểm lắm nên xin hãy quay lại ngay lập tức.',
    options: ['すぐ', 'ゆっくり', 'あとで', 'また'],
    correctIndex: 0,
    explanation: '「すぐ」 nghĩa là ngay lập tức, tức thì.'
  },
  {
    id: 'cloze_minna_14_29',
    vocabId: 'minna_14_29',
    targetWord: 'また',
    targetReading: 'また',
    sentence: '今日は楽しかったです。（　　）遊びに来てくださいね。',
    fullSentence: '今日は楽しかったです。また遊びに来てくださいね。',
    translation: 'Hôm nay thật vui. Lần sau bạn lại ghé chơi nữa nhé.',
    options: ['また', 'すぐ', 'ゆっくり', 'あまり'],
    correctIndex: 0,
    explanation: '「また」 nghĩa là lại, lần nữa, thêm một lần nữa.'
  },
  {
    id: 'cloze_minna_14_30',
    vocabId: 'minna_14_30',
    targetWord: 'あとで',
    targetReading: 'あとで',
    sentence: '今忙しいですから、（　　）電話をかけます。',
    fullSentence: '今忙しいですから、あとで電話をかけます。',
    translation: 'Bây giờ tôi đang bận nên lát nữa tôi sẽ gọi lại.',
    options: ['あとで', 'すぐ', 'ゆっくり', 'もう'],
    correctIndex: 0,
    explanation: '「あとで」 nghĩa là lát nữa, sau đó sẽ làm.'
  },
  {
    id: 'cloze_minna_14_31',
    vocabId: 'minna_14_31',
    targetWord: 'もう少し',
    targetReading: 'もうすこし',
    sentence: '（　　）大きい声で話してください。',
    fullSentence: 'もう少し大きい声で話してください。',
    translation: 'Xin hãy nói to hơn một chút nữa.',
    options: ['もう少し', 'とても', 'たくさん', '全然'],
    correctIndex: 0,
    explanation: '「もう少し」（もうすこし） nghĩa là thêm một chút nữa.'
  },
  {
    id: 'cloze_minna_14_32',
    vocabId: 'minna_14_32',
    targetWord: 'もう',
    targetReading: 'もう',
    sentence: '（　　）一杯ビールをください。',
    fullSentence: 'もう一杯ビールをください。',
    translation: 'Cho tôi thêm một cốc bia nữa.',
    options: ['もう', 'まだ', 'すぐ', 'また'],
    correctIndex: 0,
    explanation: '「もう」 đi trước số từ chỉ số lượng mang nghĩa thêm... nữa (như もう一杯: thêm một ly nữa).'
  },
  {
    id: 'cloze_minna_14_33',
    vocabId: 'minna_14_33',
    targetWord: 'いいですよ',
    targetReading: 'いいですよ',
    sentence: '「写真を撮ってもいいですか。」「ええ、（　　）。」',
    fullSentence: '「写真を撮ってもいいですか。」「ええ、いいですよ。」',
    translation: '「Tôi chụp ảnh có được không ạ?」「Vâng, được chứ ạ.」',
    options: ['いいですよ', 'だめですよ', 'すみません', 'お邪魔します'],
    correctIndex: 0,
    explanation: '「いいですよ」 dùng để vui vẻ chấp thuận hoặc đồng ý cho phép đối phương làm gì.'
  },
  {
    id: 'cloze_minna_14_34',
    vocabId: 'minna_14_34',
    targetWord: 'さあ',
    targetReading: 'さあ',
    sentence: '（　　）、時間ですから出かけましょう。',
    fullSentence: 'さあ、時間ですから出かけましょう。',
    translation: 'Nào, đến giờ rồi, chúng ta xuất phát thôi.',
    options: ['さあ', 'あれ', 'まあ', 'ええ'],
    correctIndex: 0,
    explanation: 'Thán từ 「さあ」 dùng để thúc giục, khích lệ cùng làm hành động gì đó (Nào!).'
  },
  {
    id: 'cloze_minna_14_35',
    vocabId: 'minna_14_35',
    targetWord: 'あれ',
    targetReading: 'あれ',
    sentence: '（　　）？財布がどこにもありません。',
    fullSentence: 'あれ？財布がどこにもありません。',
    translation: 'Ô kìa? Ví tiền của tôi không thấy ở đâu cả.',
    options: ['あれ', 'さあ', 'ええ', 'はい'],
    correctIndex: 0,
    explanation: 'Thán từ 「あれ？」 thể hiện sự ngạc nhiên, thắc mắc khi có điều bất thường xảy ra.'
  },
  {
    id: 'cloze_minna_14_36',
    vocabId: 'minna_14_36',
    targetWord: '信号を右へ曲がってください',
    targetReading: 'しんごうをみぎへまがってください',
    sentence: '運転手さんに「あの（　　）。」と言いました。',
    fullSentence: '運転手さんに「あの信号を右へ曲がってください。」と言いました。',
    translation: 'Tôi bảo tài xế: 「Xin hãy rẽ phải ở chỗ cột đèn tín hiệu kia.」',
    options: ['信号を右へ曲がってください', 'まっすぐ行ってください', 'ここで止めてください', 'エアコンをつけてください'],
    correctIndex: 0,
    explanation: '「信号を右へ曲がってください」 là câu hướng dẫn chỉ đường rẽ phải tại cột đèn tín hiệu giao thông.'
  },
  {
    id: 'cloze_minna_14_37',
    vocabId: 'minna_14_37',
    targetWord: 'まっすぐ',
    targetReading: 'まっすぐ',
    sentence: 'この道を（　　）行くと、右側に駅があります。',
    fullSentence: 'この道をまっすぐ行くと、右側に駅があります。',
    translation: 'Cứ đi thẳng theo con đường này thì nhà ga nằm ở phía bên tay phải.',
    options: ['まっすぐ', 'ゆっくり', '急いで', '曲がって'],
    correctIndex: 0,
    explanation: '「まっすぐ」 nghĩa là đi thẳng một mạch, thẳng tắp.'
  },
  {
    id: 'cloze_minna_14_38',
    vocabId: 'minna_14_38',
    targetWord: 'これでおねがいします',
    targetReading: 'これでおねがいします',
    sentence: 'お会計で1000円札を出して、「（　　）。」と言いました。',
    fullSentence: 'お会計で1000円札を出して、「これでおねがいします。」と言いました。',
    translation: 'Khi thanh toán tôi đưa tờ 1000 yên và nói: 「Cho tôi thanh toán bằng tiền này ạ.」',
    options: ['これでおねがいします', 'おつりをお願いします', '領収書をください', '別々にお願いします'],
    correctIndex: 0,
    explanation: '「これでおねがいします」 là câu nói khi đưa tiền hoặc thẻ để nhờ thanh toán.'
  },
  {
    id: 'cloze_minna_14_39',
    vocabId: 'minna_14_39',
    targetWord: 'お釣り',
    targetReading: 'おつり',
    sentence: 'レジで100円の（　　）をもらいました。',
    fullSentence: 'レジで100円のお釣りをもらいました。',
    translation: 'Tại quầy thu ngân tôi đã nhận 100 yên tiền thối lại.',
    options: ['お釣り', 'レシート', '切符', '細かいお金'],
    correctIndex: 0,
    explanation: '「［お］釣り」（おつり） nghĩa là tiền thừa trả lại sau khi mua hàng.'
  }
];
