import { ClozeExerciseItem } from '../../src/types/ai';

export const minna8Exercises: ClozeExerciseItem[] = [
  {
    id: 'cloze_minna_8_0',
    vocabId: 'minna_8_0',
    targetWord: 'ハンサム',
    targetReading: 'ハンサム',
    sentence: 'ミラーさんは（　　）ですね。',
    fullSentence: 'ミラーさんはハンサムですね。',
    translation: 'Anh Miller đẹp trai thật nhỉ.',
    options: ['ハンサム', 'きれい', '静か', 'にぎやか'],
    correctIndex: 0,
    explanation: '「ハンサム」 là tính từ đuôi な mượn từ tiếng Anh (handsome), có nghĩa là đẹp trai.'
  },
  {
    id: 'cloze_minna_8_1',
    vocabId: 'minna_8_1',
    targetWord: 'きれい',
    targetReading: 'きれい',
    sentence: '公園の花がとても（　　）です。',
    fullSentence: '公園の花がとてもきれいです。',
    translation: 'Hoa trong công viên rất đẹp.',
    options: ['きれい', '静か', '親切', '元気'],
    correctIndex: 0,
    explanation: '「きれい」 là tính từ đuôi な có nghĩa là đẹp hoặc sạch sẽ.'
  },
  {
    id: 'cloze_minna_8_2',
    vocabId: 'minna_8_2',
    targetWord: '静か',
    targetReading: 'しずか',
    sentence: 'この図書館はいつも（　　）です。',
    fullSentence: 'この図書館はいつも静かです。',
    translation: 'Thư viện này lúc nào cũng yên tĩnh.',
    options: ['にぎやか', '静か', '便利', 'すてき'],
    correctIndex: 1,
    explanation: '「静か」（しずか） là tính từ đuôi な có nghĩa là yên tĩnh, thanh bình.'
  },
  {
    id: 'cloze_minna_8_3',
    vocabId: 'minna_8_3',
    targetWord: 'にぎやか',
    targetReading: 'にぎやか',
    sentence: '渋谷の町はとても（　　）です。',
    fullSentence: '渋谷の町はとてもにぎやかです。',
    translation: 'Khu phố Shibuya rất nhộn nhịp, náo nhiệt.',
    options: ['静か', 'にぎやか', '暇', '親切'],
    correctIndex: 1,
    explanation: '「にぎやか」 nghĩa là nhộn nhịp, đông vui, náo nhiệt.'
  },
  {
    id: 'cloze_minna_8_4',
    vocabId: 'minna_8_4',
    targetWord: '有名',
    targetReading: 'ゆうめい',
    sentence: '富士山は（　　）な山です。',
    fullSentence: '富士山は有名な山です。',
    translation: 'Núi Phú Sĩ là một ngọn núi nổi tiếng.',
    options: ['有名', '暇', '元気', '親切'],
    correctIndex: 0,
    explanation: '「有名」（ゆうめい） nghĩa là nổi tiếng.'
  },
  {
    id: 'cloze_minna_8_5',
    vocabId: 'minna_8_5',
    targetWord: '親切',
    targetReading: 'しんせつ',
    sentence: '山田先生はとても（　　）です。',
    fullSentence: '山田先生はとても親切です。',
    translation: 'Thầy Yamada rất thân thiện và tốt bụng.',
    options: ['親切', '便利', '静か', '有名'],
    correctIndex: 0,
    explanation: '「親切」（しんせつ） biểu thị tính cách tốt bụng, tử tế, nhiệt tình giúp đỡ người khác.'
  },
  {
    id: 'cloze_minna_8_6',
    vocabId: 'minna_8_6',
    targetWord: '元気',
    targetReading: 'げんき',
    sentence: 'お父さんは（　　）ですか。…はい、元気です。',
    fullSentence: 'お父さんは元気ですか。…はい、元気です。',
    translation: 'Bố bạn có khỏe không? ...Vâng, bố tôi khỏe.',
    options: ['元気', '暇', '便利', 'きれい'],
    correctIndex: 0,
    explanation: '「元気」（げんき） nghĩa là khỏe mạnh, tràn đầy năng lượng.'
  },
  {
    id: 'cloze_minna_8_7',
    vocabId: 'minna_8_7',
    targetWord: '暇',
    targetReading: 'ひま',
    sentence: '明日は休みですから、（　　）です。',
    fullSentence: '明日は休みですから、暇です。',
    translation: 'Vì ngày mai được nghỉ nên tôi rảnh rỗi.',
    options: ['忙しい', '暇', '便利', '元気'],
    correctIndex: 1,
    explanation: '「暇」（ひま） nghĩa là rảnh rỗi, không bận việc gì.'
  },
  {
    id: 'cloze_minna_8_8',
    vocabId: 'minna_8_8',
    targetWord: '便利',
    targetReading: 'べんり',
    sentence: '地下鉄は速くて（　　）です。',
    fullSentence: '地下鉄は速くて便利です。',
    translation: 'Tàu điện ngầm vừa nhanh vừa tiện lợi.',
    options: ['不便', '便利', '暇', '静か'],
    correctIndex: 1,
    explanation: '「便利」（べんり） nghĩa là thuận tiện, tiện lợi.'
  },
  {
    id: 'cloze_minna_8_9',
    vocabId: 'minna_8_9',
    targetWord: 'すてき',
    targetReading: 'すてき',
    sentence: 'それは（　　）な時計ですね。',
    fullSentence: 'それはすてきな時計ですね。',
    translation: 'Đó là một chiếc đồng hồ tuyệt vời / đẹp đẽ nhỉ.',
    options: ['すてき', '静か', '有名', '便利'],
    correctIndex: 0,
    explanation: '「すてき」 nghĩa là tuyệt vời, rất đẹp, đáng yêu.'
  },
  {
    id: 'cloze_minna_8_10',
    vocabId: 'minna_8_10',
    targetWord: '大きい',
    targetReading: 'おおきい',
    sentence: '象は体が（　　）です。',
    fullSentence: '象は体が大きいです。',
    translation: 'Con voi có thân hình to lớn.',
    options: ['大きい', '小さい', '新しい', '古い'],
    correctIndex: 0,
    explanation: '「大きい」（おおきい） là tính từ đuôi い nghĩa là to, lớn.'
  },
  {
    id: 'cloze_minna_8_11',
    vocabId: 'minna_8_11',
    targetWord: '小さい',
    targetReading: 'ちいさい',
    sentence: 'この部屋は（　　）ですが、きれいです。',
    fullSentence: 'この部屋は小さいですが、きれいです。',
    translation: 'Căn phòng này nhỏ nhưng sạch sẽ.',
    options: ['大きい', '小さい', '高い', '低い'],
    correctIndex: 1,
    explanation: '「小さい」（ちいさい） là tính từ đuôi い nghĩa là nhỏ bé.'
  },
  {
    id: 'cloze_minna_8_12',
    vocabId: 'minna_8_12',
    targetWord: '新しい',
    targetReading: 'あたらしい',
    sentence: '先週（　　）車を買いました。',
    fullSentence: '先週新しい車を買いました。',
    translation: 'Tuần trước tôi đã mua một chiếc xe ô tô mới.',
    options: ['新しい', '古い', '悪い', '暑い'],
    correctIndex: 0,
    explanation: '「新しい」（あたらしい） nghĩa là mới.'
  },
  {
    id: 'cloze_minna_8_13',
    vocabId: 'minna_8_13',
    targetWord: '古い',
    targetReading: 'ふるい',
    sentence: 'このお寺はとても（　　）です。',
    fullSentence: 'このお寺はとても古いです。',
    translation: 'Ngôi chùa này rất cổ kính / cũ.',
    options: ['新しい', '古い', '寒い', '高い'],
    correctIndex: 1,
    explanation: '「古い」（ふるい） là tính từ đuôi い dùng cho đồ vật, công trình kiến trúc có nghĩa là cũ, cổ kính.'
  },
  {
    id: 'cloze_minna_8_14',
    vocabId: 'minna_8_14',
    targetWord: 'いい',
    targetReading: 'いい',
    sentence: '今日はとても（　　）天気ですね。',
    fullSentence: '今日はとてもいい天気ですね。',
    translation: 'Hôm nay thời tiết đẹp / tốt thật nhỉ.',
    options: ['いい', '悪い', '古い', '暑い'],
    correctIndex: 0,
    explanation: '「いい」（よい） nghĩa là tốt, đẹp.'
  },
  {
    id: 'cloze_minna_8_15',
    vocabId: 'minna_8_15',
    targetWord: '悪い',
    targetReading: 'わるい',
    sentence: '雨が降って、天気が（　　）なりました。',
    fullSentence: '雨が降って、天気が悪くなりました。',
    translation: 'Trời mưa nên thời tiết đã trở nên xấu.',
    options: ['良く', '悪く', '高く', '安く'],
    correctIndex: 1,
    explanation: '「悪い」（わるい） nghĩa là xấu, tồi tệ. Ở đây chia thành 「悪く」 khi đi với 「なりました」.'
  },
  {
    id: 'cloze_minna_8_16',
    vocabId: 'minna_8_16',
    targetWord: '暑い',
    targetReading: 'あつい',
    sentence: '日本の夏はとても（　　）です。',
    fullSentence: '日本の夏はとても暑いです。',
    translation: 'Mùa hè ở Nhật Bản rất nóng bức.',
    options: ['暑い', '寒い', '冷たい', '涼しい'],
    correctIndex: 0,
    explanation: '「暑い」（あつい） nghĩa là nóng (thời tiết).'
  },
  {
    id: 'cloze_minna_8_17',
    vocabId: 'minna_8_17',
    targetWord: '寒い',
    targetReading: 'さむい',
    sentence: '北海道の冬はとても（　　）です。',
    fullSentence: '北海道の冬はとても寒いです。',
    translation: 'Mùa đông ở Hokkaido rất lạnh.',
    options: ['暑い', '寒い', '温かい', '高い'],
    correctIndex: 1,
    explanation: '「寒い」（さむい） nghĩa là lạnh (nhiệt độ thời tiết).'
  },
  {
    id: 'cloze_minna_8_18',
    vocabId: 'minna_8_18',
    targetWord: '冷たい',
    targetReading: 'つめたい',
    sentence: '暑いですから、（　　）お茶を飲みます。',
    fullSentence: '暑いですから、冷たいお茶を飲みます。',
    translation: 'Vì trời nóng nên tôi uống trà lạnh.',
    options: ['冷たい', '寒い', '熱い', '古い'],
    correctIndex: 0,
    explanation: '「冷たい」（つめたい） nghĩa là lạnh buốt khi chạm vào đồ vật hoặc đồ uống mát lạnh.'
  },
  {
    id: 'cloze_minna_8_19',
    vocabId: 'minna_8_19',
    targetWord: '難しい',
    targetReading: 'むずかしい',
    sentence: '日本語の漢字は（　　）です。',
    fullSentence: '日本語の漢字は難しいです。',
    translation: 'Chữ Hán tiếng Nhật rất khó.',
    options: ['易しい', '難しい', '面白い', '高い'],
    correctIndex: 1,
    explanation: '「難しい」（むずかしい） nghĩa là khó khăn, phức tạp.'
  },
  {
    id: 'cloze_minna_8_20',
    vocabId: 'minna_8_20',
    targetWord: '易しい',
    targetReading: 'やさしい',
    sentence: 'ひらがなは漢字より（　　）です。',
    fullSentence: 'ひらがなは漢字より易しいです。',
    translation: 'Chữ Hiragana dễ hơn chữ Hán.',
    options: ['易しい', '難しい', '新しい', '古い'],
    correctIndex: 0,
    explanation: '「易しい」（やさしい） nghĩa là dễ dàng, đơn giản.'
  },
  {
    id: 'cloze_minna_8_21',
    vocabId: 'minna_8_21',
    targetWord: '高い',
    targetReading: 'たかい',
    sentence: 'このカメラはとても（　　）です。50万円です。',
    fullSentence: 'このカメラはとても高いです。50万円です。',
    translation: 'Chiếc máy ảnh này rất đắt. Giá 50 vạn yên.',
    options: ['安い', '高い', '低い', '小さい'],
    correctIndex: 1,
    explanation: '「高い」（たかい） nghĩa là đắt (về giá cả) hoặc cao (về chiều cao).'
  },
  {
    id: 'cloze_minna_8_22',
    vocabId: 'minna_8_22',
    targetWord: '安い',
    targetReading: 'やすい',
    sentence: 'あのスーパーの野菜はいつも（　　）です。',
    fullSentence: 'あのスーパーの野菜はいつも安いです。',
    translation: 'Rau ở siêu thị kia lúc nào cũng rẻ.',
    options: ['高い', '安い', '悪い', '古い'],
    correctIndex: 1,
    explanation: '「安い」（やすい） nghĩa là rẻ (giá cả phải chăng).'
  },
  {
    id: 'cloze_minna_8_23',
    vocabId: 'minna_8_23',
    targetWord: '低い',
    targetReading: 'ひくい',
    sentence: '私の部屋の天井は（　　）です。',
    fullSentence: '私の部屋の天井は低いです。',
    translation: 'Trần phòng của tôi khá thấp.',
    options: ['高い', '低い', '長い', '重い'],
    correctIndex: 1,
    explanation: '「低い」（ひくい） nghĩa là thấp (chiều cao, độ cao).'
  },
  {
    id: 'cloze_minna_8_24',
    vocabId: 'minna_8_24',
    targetWord: 'おもしろい',
    targetReading: 'おもしろい',
    sentence: '昨日（　　）本を読みました。',
    fullSentence: '昨日おもしろい本を読みました。',
    translation: 'Hôm qua tôi đã đọc một cuốn sách thú vị.',
    options: ['おもしろい', 'つまらない', 'おいしい', '忙しい'],
    correctIndex: 0,
    explanation: '「おもしろい」 nghĩa là hay, thú vị, hấp dẫn.'
  },
  {
    id: 'cloze_minna_8_25',
    vocabId: 'minna_8_25',
    targetWord: 'おいしい',
    targetReading: 'おいしい',
    sentence: '日本のラーメンはとても（　　）です。',
    fullSentence: '日本のラーメンはとてもおいしいです。',
    translation: 'Món mì Ramen của Nhật Bản rất ngon.',
    options: ['おいしい', 'まずい', '高い', '忙しい'],
    correctIndex: 0,
    explanation: '「おいしい」 nghĩa là ngon miệng.'
  },
  {
    id: 'cloze_minna_8_26',
    vocabId: 'minna_8_26',
    targetWord: '忙しい',
    targetReading: 'いそがしい',
    sentence: '仕事がたくさんありますから、今週は（　　）です。',
    fullSentence: '仕事がたくさんありますから、今週は忙しいです。',
    translation: 'Vì có nhiều công việc nên tuần này tôi rất bận rộn.',
    options: ['暇', '忙しい', '楽しい', '優しい'],
    correctIndex: 1,
    explanation: '「忙しい」（いそがしい） nghĩa là bận rộn, tất bật.'
  },
  {
    id: 'cloze_minna_8_27',
    vocabId: 'minna_8_27',
    targetWord: '楽しい',
    targetReading: 'たのしい',
    sentence: '昨日のパーティーはとても（　　）でした。',
    fullSentence: '昨日のパーティーはとても楽しいでした。',
    translation: 'Bữa tiệc ngày hôm qua đã rất vui vẻ.',
    options: ['楽しい', '忙しい', '寒い', '悪い'],
    correctIndex: 0,
    explanation: '「楽しい」（たのしい） nghĩa là vui vẻ, thú vị, mang lại niềm vui.'
  },
  {
    id: 'cloze_minna_8_28',
    vocabId: 'minna_8_28',
    targetWord: '白い',
    targetReading: 'しろい',
    sentence: '冬になると、山は（　　）雪に覆われます。',
    fullSentence: '冬になると、山は白い雪に覆われます。',
    translation: 'Mỗi khi mùa đông đến, ngọn núi lại được phủ bởi tuyết trắng.',
    options: ['白い', '黒い', '赤い', '青い'],
    correctIndex: 0,
    explanation: '「白い」（しろい） là tính từ chỉ màu trắng.'
  },
  {
    id: 'cloze_minna_8_29',
    vocabId: 'minna_8_29',
    targetWord: '黒い',
    targetReading: 'くろい',
    sentence: 'ミラーさんは（　　）靴を履いています。',
    fullSentence: 'ミラーさんは黒い靴を履いています。',
    translation: 'Anh Miller đang đi một đôi giày màu đen.',
    options: ['黒い', '白い', '赤い', '青い'],
    correctIndex: 0,
    explanation: '「黒い」（くろい） là tính từ chỉ màu đen.'
  },
  {
    id: 'cloze_minna_8_30',
    vocabId: 'minna_8_30',
    targetWord: '赤い',
    targetReading: 'あかい',
    sentence: '彼女は（　　）りんごを食べました。',
    fullSentence: '彼女は赤いりんごを食べました。',
    translation: 'Cô ấy đã ăn quả táo màu đỏ.',
    options: ['赤い', '青い', '黒い', '白い'],
    correctIndex: 0,
    explanation: '「赤い」（あかい） là tính từ chỉ màu đỏ.'
  },
  {
    id: 'cloze_minna_8_31',
    vocabId: 'minna_8_31',
    targetWord: '青い',
    targetReading: 'あおい',
    sentence: '海はとても（　　）ですね。',
    fullSentence: '海はとても青いですね。',
    translation: 'Biển xanh biếc thật đẹp nhỉ.',
    options: ['青い', '赤い', '黒い', '白い'],
    correctIndex: 0,
    explanation: '「青い」（あおい） là tính từ chỉ màu xanh da trời, xanh nước biển.'
  },
  {
    id: 'cloze_minna_8_32',
    vocabId: 'minna_8_32',
    targetWord: '桜',
    targetReading: 'さくら',
    sentence: '春に公園で（　　）の花を見ます。',
    fullSentence: '春に公園で桜の花を見ます。',
    translation: 'Vào mùa xuân, tôi ngắm hoa anh đào ở công viên.',
    options: ['桜', '山', '町', '車'],
    correctIndex: 0,
    explanation: '「桜」（さくら） nghĩa là hoa anh đào, loài hoa biểu tượng của nước Nhật.'
  },
  {
    id: 'cloze_minna_8_33',
    vocabId: 'minna_8_33',
    targetWord: '山',
    targetReading: 'やま',
    sentence: '休みの日に（　　）へ登ります。',
    fullSentence: '休みの日に山へ登ります。',
    translation: 'Vào ngày nghỉ tôi đi leo núi.',
    options: ['山', '桜', '町', '寮'],
    correctIndex: 0,
    explanation: '「山」（やま） nghĩa là ngọn núi.'
  },
  {
    id: 'cloze_minna_8_34',
    vocabId: 'minna_8_34',
    targetWord: '町',
    targetReading: 'まち',
    sentence: '私の（　　）は静かできれいな所です。',
    fullSentence: '私の町は静かできれいな所です。',
    translation: 'Thị trấn / khu phố của tôi là một nơi yên bình và sạch sẽ.',
    options: ['町', '山', '桜', '車'],
    correctIndex: 0,
    explanation: '「町」（まち） nghĩa là thị trấn, con phố, thành phố nhỏ.'
  },
  {
    id: 'cloze_minna_8_35',
    vocabId: 'minna_8_35',
    targetWord: '食べ物',
    targetReading: 'たべもの',
    sentence: '日本の（　　）はおいしいですが、高いです。',
    fullSentence: '日本の食べ物はおいしいですが、高いです。',
    translation: 'Đồ ăn Nhật Bản ngon nhưng đắt.',
    options: ['食べ物', '飲み物', '車', '町'],
    correctIndex: 0,
    explanation: '「食べ物」（たべもの） nghĩa là đồ ăn, thức ăn.'
  },
  {
    id: 'cloze_minna_8_36',
    vocabId: 'minna_8_36',
    targetWord: '車',
    targetReading: 'くるま',
    sentence: '父の（　　）は黒いホンダです。',
    fullSentence: '父の車は黒いホンダです。',
    translation: 'Xe ô tô của bố tôi là một chiếc Honda màu đen.',
    options: ['車', '町', '寮', '所'],
    correctIndex: 0,
    explanation: '「車」（くるま） nghĩa là xe hơi, xe ô tô.'
  },
  {
    id: 'cloze_minna_8_37',
    vocabId: 'minna_8_37',
    targetWord: '所',
    targetReading: 'ところ',
    sentence: '京都はとても有名な（　　）です。',
    fullSentence: '京都はとても有名な所です。',
    translation: 'Kyoto là một địa danh / nơi chốn rất nổi tiếng.',
    options: ['所', '車', '山', '寮'],
    correctIndex: 0,
    explanation: '「所」（ところ） nghĩa là nơi chốn, địa điểm.'
  },
  {
    id: 'cloze_minna_8_38',
    vocabId: 'minna_8_38',
    targetWord: '寮',
    targetReading: 'りょう',
    sentence: '留学生はみんな大学の（　　）に住んでいます。',
    fullSentence: '留学生はみんな大学の寮に住んでいます。',
    translation: 'Các lưu học sinh đều đang sống trong ký túc xá của trường đại học.',
    options: ['寮', '町', '山', '所'],
    correctIndex: 0,
    explanation: '「寮」（りょう） nghĩa là ký túc xá.'
  },
  {
    id: 'cloze_minna_8_39',
    vocabId: 'minna_8_39',
    targetWord: '勉強',
    targetReading: 'べんきょう',
    sentence: '毎晩日本語の（　　）をします。',
    fullSentence: '毎晩日本語の勉強をします。',
    translation: 'Mỗi tối tôi đều học tiếng Nhật.',
    options: ['勉強', '仕事', '生活', '料理'],
    correctIndex: 0,
    explanation: '「勉強」（べんきょう） nghĩa là việc học tập.'
  },
  {
    id: 'cloze_minna_8_40',
    vocabId: 'minna_8_40',
    targetWord: '生活',
    targetReading: 'せいかつ',
    sentence: '日本での（　　）はどうですか。…とても楽しいです。',
    fullSentence: '日本での生活はどうですか。…とても楽しいです。',
    translation: 'Cuộc sống ở Nhật Bản thế nào? ...Rất vui vẻ.',
    options: ['生活', '勉強', '仕事', '旅行'],
    correctIndex: 0,
    explanation: '「生活」（せいかつ） nghĩa là cuộc sống, đời sống sinh hoạt.'
  },
  {
    id: 'cloze_minna_8_41',
    vocabId: 'minna_8_41',
    targetWord: '仕事',
    targetReading: 'しごと',
    sentence: 'お父さんの（　　）は何ですか。…銀行員です。',
    fullSentence: 'お父さんの仕事は何ですか。…銀行員です。',
    translation: 'Công việc của bố bạn là gì? ...Là nhân viên ngân hàng.',
    options: ['仕事', '生活', '勉強', '所'],
    correctIndex: 0,
    explanation: '「［お］仕事」（しごと） nghĩa là công việc, nghề nghiệp.'
  },
  {
    id: 'cloze_minna_8_42',
    vocabId: 'minna_8_42',
    targetWord: 'どう',
    targetReading: 'どう',
    sentence: '大学の寮の部屋は（　　）ですか。…静かです。',
    fullSentence: '大学の寮の部屋はどうですか。…静かです。',
    translation: 'Phòng ký túc xá đại học thế nào? ...Yên tĩnh lắm.',
    options: ['どう', 'どれ', 'どこ', 'だれ'],
    correctIndex: 0,
    explanation: 'Nghi vấn từ 「どう」 dùng để hỏi về tính chất, trạng thái hoặc cảm tưởng (như thế nào).'
  },
  {
    id: 'cloze_minna_8_43',
    vocabId: 'minna_8_43',
    targetWord: 'どんな',
    targetReading: 'どんな',
    sentence: '京都は（　　）町ですか。…古い町です。',
    fullSentence: '京都はどんな町ですか。…古い町です。',
    translation: 'Kyoto là một thành phố như thế nào? ...Là một thành phố cổ kính.',
    options: ['どんな', 'どう', 'どれ', 'どちら'],
    correctIndex: 0,
    explanation: '「どんな」 đứng trước danh từ để hỏi tính chất, đặc điểm của người hoặc sự vật (loại nào, như thế nào).'
  },
  {
    id: 'cloze_minna_8_44',
    vocabId: 'minna_8_44',
    targetWord: 'どれ',
    targetReading: 'どれ',
    sentence: 'あなたの傘は（　　）ですか。…あの青い傘です。',
    fullSentence: 'あなたの傘はどれですか。…あの青い傘です。',
    translation: 'Chiếc ô của bạn là cái nào? ...Là chiếc ô màu xanh kia.',
    options: ['どれ', 'どんな', 'どう', 'だれ'],
    correctIndex: 0,
    explanation: '「どれ」 dùng để hỏi chọn ra một vật cụ thể trong số ba vật trở lên (cái nào).'
  },
  {
    id: 'cloze_minna_8_45',
    vocabId: 'minna_8_45',
    targetWord: 'とても',
    targetReading: 'とても',
    sentence: '富士山は（　　）きれいです。',
    fullSentence: '富士山はとてもきれいです。',
    translation: 'Núi Phú Sĩ rất đẹp.',
    options: ['とても', 'あまり', '少し', '全然'],
    correctIndex: 0,
    explanation: 'Phó từ 「とても」 đứng trước tính từ khẳng định để chỉ mức độ cao (rất).'
  },
  {
    id: 'cloze_minna_8_46',
    vocabId: 'minna_8_46',
    targetWord: 'あまり',
    targetReading: 'あまり',
    sentence: 'この町は（　　）にぎやかじゃありません。',
    fullSentence: 'この町はあまりにぎやかじゃありません。',
    translation: 'Thị trấn này không nhộn nhịp lắm.',
    options: ['とても', 'あまり', 'いつも', 'たくさん'],
    correctIndex: 1,
    explanation: 'Phó từ 「あまり」 đi với câu phủ định mang nghĩa là không... lắm.'
  },
  {
    id: 'cloze_minna_8_47',
    vocabId: 'minna_8_47',
    targetWord: 'そして',
    targetReading: 'そして',
    sentence: '日本の食べ物はおいしいです。（　　）、きれいです。',
    fullSentence: '日本の食べ物はおいしいです。そして、きれいです。',
    translation: 'Đồ ăn Nhật Bản ngon. Và hơn nữa, rất đẹp mắt.',
    options: ['そして', 'しかし', 'ですが', 'だから'],
    correctIndex: 0,
    explanation: 'Liên từ 「そして」 dùng để nối hai câu tương đồng ý nghĩa (và, thêm nữa).'
  },
  {
    id: 'cloze_minna_8_48',
    vocabId: 'minna_8_48',
    targetWord: 'が',
    targetReading: 'が',
    sentence: '日本の食べ物はおいしいです（　　）、高いです。',
    fullSentence: '日本の食べ物はおいしいですが、高いです。',
    translation: 'Đồ ăn Nhật Bản ngon nhưng đắt.',
    options: ['が', 'から', 'そして', 'と'],
    correctIndex: 0,
    explanation: 'Trợ từ nối 「が」 dùng để nối hai vế mang ý nghĩa tương phản, đối lập (nhưng).'
  }
];
