import { ClozeExerciseItem } from '../../src/types/ai';

export const minna9Exercises: ClozeExerciseItem[] = [
  {
    id: 'cloze_minna_9_0',
    vocabId: 'minna_9_0',
    targetWord: 'わかります',
    targetReading: 'わかります',
    sentence: '私は英語が少し（　　）。',
    fullSentence: '私は英語が少しわかります。',
    translation: 'Tôi hiểu một chút tiếng Anh.',
    options: ['わかります', 'あります', 'できます', '知ります'],
    correctIndex: 0,
    explanation: '「わかります」 đi với trợ từ が biểu thị sự hiểu biết, nắm rõ nội dung (hiểu).'
  },
  {
    id: 'cloze_minna_9_1',
    vocabId: 'minna_9_1',
    targetWord: 'あります',
    targetReading: 'あります',
    sentence: '私は車が（　　）。',
    fullSentence: '私は車があります。',
    translation: 'Tôi có xe ô tô.',
    options: ['あります', 'います', '買います', '乗ります'],
    correctIndex: 0,
    explanation: '「あります」 đi với trợ từ が mang nghĩa sở hữu đồ vật (có).'
  },
  {
    id: 'cloze_minna_9_2',
    vocabId: 'minna_9_2',
    targetWord: '好き',
    targetReading: 'すき',
    sentence: '私は日本の食べ物が（　　）です。',
    fullSentence: '私は日本の食べ物が好きです。',
    translation: 'Tôi thích đồ ăn Nhật Bản.',
    options: ['好き', '嫌い', '上手', '下手'],
    correctIndex: 0,
    explanation: '「好き」（すき） là tính từ đuôi な biểu thị sở thích (thích cái gì đó: ～が好きです).'
  },
  {
    id: 'cloze_minna_9_3',
    vocabId: 'minna_9_3',
    targetWord: '嫌い',
    targetReading: 'きらい',
    sentence: '弟は野菜が（　　）です。',
    fullSentence: '弟は野菜が嫌いです。',
    translation: 'Em trai tôi ghét rau.',
    options: ['嫌い', '好き', '上手', '下手'],
    correctIndex: 0,
    explanation: '「嫌い」（きらい） là tính từ đuôi な biểu thị sự không thích, ghét (～が嫌いです).'
  },
  {
    id: 'cloze_minna_9_4',
    vocabId: 'minna_9_4',
    targetWord: '上手',
    targetReading: 'じょうず',
    sentence: 'マリアさんは料理が（　　）ですね。',
    fullSentence: 'マリアさんは料理が上手ですね。',
    translation: 'Bạn Maria nấu ăn giỏi thật đấy nhỉ.',
    options: ['上手', '下手', '好き', '苦手'],
    correctIndex: 0,
    explanation: '「上手」（じょうず） nghĩa là giỏi, khéo léo trong một lĩnh vực hoặc kỹ năng nào đó.'
  },
  {
    id: 'cloze_minna_9_5',
    vocabId: 'minna_9_5',
    targetWord: '下手',
    targetReading: 'へた',
    sentence: '私はテニスが（　　）です。',
    fullSentence: '私はテニスが下手です。',
    translation: 'Tôi chơi quần vợt dở / kém.',
    options: ['下手', '上手', 'きれい', '有名'],
    correctIndex: 0,
    explanation: '「下手」（へた） nghĩa là dở, kém, vụng về trong một kỹ năng.'
  },
  {
    id: 'cloze_minna_9_6',
    vocabId: 'minna_9_6',
    targetWord: '料理',
    targetReading: 'りょうり',
    sentence: '母の（　　）はいつもおいしいです。',
    fullSentence: '母の料理はいつもおいしいです。',
    translation: 'Món ăn mẹ nấu lúc nào cũng ngon.',
    options: ['料理', '飲み物', 'スポーツ', '音楽'],
    correctIndex: 0,
    explanation: '「料理」（りょうり） nghĩa là món ăn hoặc việc nấu nướng.'
  },
  {
    id: 'cloze_minna_9_7',
    vocabId: 'minna_9_7',
    targetWord: '飲み物',
    targetReading: 'のみもの',
    sentence: '何か冷たい（　　）を買いましょう。',
    fullSentence: '何か冷たい飲み物を買いましょう。',
    translation: 'Chúng ta hãy mua thức uống gì đó mát lạnh đi.',
    options: ['飲み物', '食べ物', '果物', '品物'],
    correctIndex: 0,
    explanation: '「飲み物」（のみもの） nghĩa là đồ uống, thức uống.'
  },
  {
    id: 'cloze_minna_9_8',
    vocabId: 'minna_9_8',
    targetWord: 'スポーツ',
    targetReading: 'スポーツ',
    sentence: 'どんな（　　）が好きですか。…サッカーが好きです。',
    fullSentence: 'どんなスポーツが好きですか。…サッカーが好きです。',
    translation: 'Bạn thích môn thể thao nào? ...Tôi thích bóng đá.',
    options: ['スポーツ', '音楽', '料理', '絵'],
    correctIndex: 0,
    explanation: '「スポーツ」 nghĩa là thể thao.'
  },
  {
    id: 'cloze_minna_9_9',
    vocabId: 'minna_9_9',
    targetWord: '野球',
    targetReading: 'やきゅう',
    sentence: '日本人は（　　）がとても好きです。',
    fullSentence: '日本人は野球がとても好きです。',
    translation: 'Người Nhật Bản rất thích bóng chày.',
    options: ['野球', 'ダンス', 'カラオケ', '絵'],
    correctIndex: 0,
    explanation: '「野球」（やきゅう） nghĩa là môn bóng chày.'
  },
  {
    id: 'cloze_minna_9_10',
    vocabId: 'minna_9_10',
    targetWord: 'ダンス',
    targetReading: 'ダンス',
    sentence: '友達と一緒に（　　）を習います。',
    fullSentence: '友達と一緒にダンスを習います。',
    translation: 'Tôi học khiêu vũ / nhảy múa cùng với bạn.',
    options: ['ダンス', '野球', '歌舞伎', 'クラシック'],
    correctIndex: 0,
    explanation: '「ダンス」 nghĩa là khiêu vũ, nhảy múa.'
  },
  {
    id: 'cloze_minna_9_11',
    vocabId: 'minna_9_11',
    targetWord: '音楽',
    targetReading: 'おんがく',
    sentence: '部屋で（　　）を聞きながら勉強します。',
    fullSentence: '部屋で音楽を聞きながら勉強します。',
    translation: 'Tôi vừa nghe âm nhạc trong phòng vừa học bài.',
    options: ['音楽', 'スポーツ', '料理', 'チケット'],
    correctIndex: 0,
    explanation: '「音楽」（おんがく） nghĩa là âm nhạc.'
  },
  {
    id: 'cloze_minna_9_12',
    vocabId: 'minna_9_12',
    targetWord: '歌',
    targetReading: 'うた',
    sentence: '日本の（　　）を歌いましょう。',
    fullSentence: '日本の歌を歌いましょう。',
    translation: 'Chúng ta cùng hát một bài hát tiếng Nhật nào.',
    options: ['歌', '絵', '字', '本'],
    correctIndex: 0,
    explanation: '「歌」（うた） nghĩa là bài hát.'
  },
  {
    id: 'cloze_minna_9_13',
    vocabId: 'minna_9_13',
    targetWord: 'クラシック',
    targetReading: 'クラシック',
    sentence: '父は（　　）音楽が好きです。',
    fullSentence: '父はクラシック音楽が好きです。',
    translation: 'Bố tôi thích nhạc cổ điển.',
    options: ['クラシック', 'ジャズ', 'カラオケ', 'コンサート'],
    correctIndex: 0,
    explanation: '「クラシック」 nghĩa là nhạc cổ điển.'
  },
  {
    id: 'cloze_minna_9_14',
    vocabId: 'minna_9_14',
    targetWord: 'ジャズ',
    targetReading: 'ジャズ',
    sentence: 'カフェで静かな（　　）が流れています。',
    fullSentence: 'カフェで静かなジャズが流れています。',
    translation: 'Tại quán cà phê đang phát một bản nhạc jazz êm dịu.',
    options: ['ジャズ', 'クラシック', '野球', '歌舞伎'],
    correctIndex: 0,
    explanation: '「ジャズ」 nghĩa là nhạc jazz.'
  },
  {
    id: 'cloze_minna_9_15',
    vocabId: 'minna_9_15',
    targetWord: 'コンサート',
    targetReading: 'コンサート',
    sentence: '明日東京ドームの（　　）に行きます。',
    fullSentence: '明日東京ドームのコンサートに行きます。',
    translation: 'Ngày mai tôi sẽ đi xem buổi hòa nhạc ở Tokyo Dome.',
    options: ['コンサート', 'カラオケ', 'スポーツ', 'ダンス'],
    correctIndex: 0,
    explanation: '「コンサート」 nghĩa là buổi hòa nhạc, đêm nhạc biểu diễn.'
  },
  {
    id: 'cloze_minna_9_16',
    vocabId: 'minna_9_16',
    targetWord: 'カラオケ',
    targetReading: 'カラオケ',
    sentence: '金曜日の夜、みんなで（　　）へ行きました。',
    fullSentence: '金曜日の夜、みんなでカラオケへ行きました。',
    translation: 'Tối thứ sáu mọi người đã cùng nhau đi hát karaoke.',
    options: ['カラオケ', '歌舞伎', 'コンサート', '野球'],
    correctIndex: 0,
    explanation: '「カラオケ」 nghĩa là quán hát hoặc dịch vụ hát karaoke.'
  },
  {
    id: 'cloze_minna_9_17',
    vocabId: 'minna_9_17',
    targetWord: '歌舞伎',
    targetReading: 'かぶき',
    sentence: '銀座の劇場で（　　）を見ました。',
    fullSentence: '銀座の劇場で歌舞伎を見ました。',
    translation: 'Tôi đã xem kịch Kabuki ở nhà hát tại Ginza.',
    options: ['歌舞伎', 'カラオケ', 'ダンス', 'ジャズ'],
    correctIndex: 0,
    explanation: '「歌舞伎」（かぶき） là môn nghệ thuật kịch truyền thống nổi tiếng của Nhật Bản.'
  },
  {
    id: 'cloze_minna_9_18',
    vocabId: 'minna_9_18',
    targetWord: '絵',
    targetReading: 'え',
    sentence: '美術館で有名な（　　）を見ました。',
    fullSentence: '美術館で有名な絵を見ました。',
    translation: 'Tôi đã xem những bức tranh nổi tiếng ở bảo tàng mỹ thuật.',
    options: ['絵', '字', '歌', '本'],
    correctIndex: 0,
    explanation: '「絵」（え） nghĩa là tranh vẽ, bức tranh.'
  },
  {
    id: 'cloze_minna_9_19',
    vocabId: 'minna_9_19',
    targetWord: '字',
    targetReading: 'じ',
    sentence: '田中さんの（　　）はとてもきれいです。',
    fullSentence: '田中さんの字はとてもきれいです。',
    translation: 'Chữ viết của bạn Tanaka rất đẹp.',
    options: ['字', '絵', '歌', '声'],
    correctIndex: 0,
    explanation: '「字」（じ） nghĩa là chữ viết, nét chữ.'
  },
  {
    id: 'cloze_minna_9_20',
    vocabId: 'minna_9_20',
    targetWord: '漢字',
    targetReading: 'かんじ',
    sentence: 'この（　　）の読み方を教えてください。',
    fullSentence: 'この漢字の読み方を教えてください。',
    translation: 'Xin vui lòng chỉ cho tôi cách đọc chữ Hán này.',
    options: ['漢字', 'ローマ字', 'ひらがな', 'かたかな'],
    correctIndex: 0,
    explanation: '「漢字」（かんじ） nghĩa là chữ Hán (Kanji).'
  },
  {
    id: 'cloze_minna_9_21',
    vocabId: 'minna_9_21',
    targetWord: 'ひらがな',
    targetReading: 'ひらがな',
    sentence: '外国人学習者はまず（　　）を覚えます。',
    fullSentence: '外国人学習者はまずひらがなを覚えます。',
    translation: 'Người nước ngoài học tiếng Nhật trước tiên sẽ nhớ bảng chữ Hiragana.',
    options: ['ひらがな', '漢字', 'かたかな', 'ローマ字'],
    correctIndex: 0,
    explanation: '「ひらがな」 là hệ chữ mềm cơ bản của tiếng Nhật.'
  },
  {
    id: 'cloze_minna_9_22',
    vocabId: 'minna_9_22',
    targetWord: 'かたかな',
    targetReading: 'かたかな',
    sentence: '外来語は（　　）で書きます。',
    fullSentence: '外来語はかたかなで書きます。',
    translation: 'Từ mượn tiếng nước ngoài được viết bằng chữ Katakana.',
    options: ['かたかな', 'ひらがな', '漢字', 'ローマ字'],
    correctIndex: 0,
    explanation: '「かたかな」 là hệ chữ cứng của tiếng Nhật dùng viết từ ngoại lai.'
  },
  {
    id: 'cloze_minna_9_23',
    vocabId: 'minna_9_23',
    targetWord: 'ローマ字',
    targetReading: 'ローマじ',
    sentence: 'パソコンのキーボードで（　　）を入力します。',
    fullSentence: 'パソコンのキーボードでローマ字を入力します。',
    translation: 'Tôi nhập chữ Romaji (chữ La-tinh) trên bàn phím máy tính.',
    options: ['ローマ字', '漢字', 'ひらがな', 'かたかな'],
    correctIndex: 0,
    explanation: '「ローマ字」（ローマじ） nghĩa là chữ cái La-tinh.'
  },
  {
    id: 'cloze_minna_9_24',
    vocabId: 'minna_9_24',
    targetWord: '細かいお金',
    targetReading: 'こまかいおかね',
    sentence: 'バスに乗りますから、（　　）がありますか。',
    fullSentence: 'バスに乗りますから、細かいお金がありますか。',
    translation: 'Vì sắp lên xe buýt nên bạn có tiền lẻ không?',
    options: ['細かいお金', '大きいお金', 'チケット', 'カード'],
    correctIndex: 0,
    explanation: '「細かいお金」（こまかいおかね） nghĩa là tiền lẻ.'
  },
  {
    id: 'cloze_minna_9_25',
    vocabId: 'minna_9_25',
    targetWord: 'チケット',
    targetReading: 'チケット',
    sentence: '映画の（　　）を2枚買いました。',
    fullSentence: '映画のチケットを2枚買いました。',
    translation: 'Tôi đã mua 2 vé xem phim.',
    options: ['チケット', 'お金', '本', '手紙'],
    correctIndex: 0,
    explanation: '「チケット」 nghĩa là vé (xem phim, vé hòa nhạc, vé máy bay).'
  },
  {
    id: 'cloze_minna_9_26',
    vocabId: 'minna_9_26',
    targetWord: '時間',
    targetReading: 'じかん',
    sentence: '忙しいですから、（　　）がありません。',
    fullSentence: '忙しいですから、時間がありません。',
    translation: 'Vì bận rộn nên tôi không có thời gian.',
    options: ['時間', '用事', '約束', 'お金'],
    correctIndex: 0,
    explanation: '「時間」（じかん） nghĩa là thời gian.'
  },
  {
    id: 'cloze_minna_9_27',
    vocabId: 'minna_9_27',
    targetWord: '用事',
    targetReading: 'ようじ',
    sentence: '今日は市役所へ（　　）に行きます。',
    fullSentence: '今日は市役所へ用事に行きます。',
    translation: 'Hôm nay tôi đến tòa thị chính vì có việc bận / việc riêng.',
    options: ['用事', '約束', '時間', '仕事'],
    correctIndex: 0,
    explanation: '「用事」（ようじ） nghĩa là việc bận, công chuyện riêng cần giải quyết.'
  },
  {
    id: 'cloze_minna_9_28',
    vocabId: 'minna_9_28',
    targetWord: '約束',
    targetReading: 'やくそく',
    sentence: '今夜友達と会う（　　）があります。',
    fullSentence: '今夜友達と会う約束があります。',
    translation: 'Tối nay tôi có hẹn gặp bạn bè.',
    options: ['約束', '用事', '時間', '仕事'],
    correctIndex: 0,
    explanation: '「約束」（やくそく） nghĩa là lời hứa hoặc cuộc hẹn.'
  },
  {
    id: 'cloze_minna_9_29',
    vocabId: 'minna_9_29',
    targetWord: 'ご主人',
    targetReading: 'ごしゅじん',
    sentence: '佐藤さんの（　　）は会社の社長です。',
    fullSentence: '佐藤さんのご主人は会社の社長です。',
    translation: 'Chồng của chị Sato là giám đốc công ty.',
    options: ['ご主人', '夫', '奥さん', '妻'],
    correctIndex: 0,
    explanation: '「ご主人」（ごしゅじん） là cách gọi chồng của người khác một cách lịch sự.'
  },
  {
    id: 'cloze_minna_9_30',
    vocabId: 'minna_9_30',
    targetWord: '夫',
    targetReading: 'おっと',
    sentence: '私の（　　）は毎朝7時に出勤します。',
    fullSentence: '私の夫は毎朝7時に出勤します。',
    translation: 'Chồng tôi mỗi sáng đều đi làm lúc 7 giờ.',
    options: ['夫', 'ご主人', '奥さん', '妻'],
    correctIndex: 0,
    explanation: '「夫」（おっと） hoặc 「主人」 dùng khi người nói xưng hô về chồng của chính mình.'
  },
  {
    id: 'cloze_minna_9_31',
    vocabId: 'minna_9_31',
    targetWord: '奥さん',
    targetReading: 'おくさん',
    sentence: 'ミラーさんの（　　）は親切で優しい人です。',
    fullSentence: 'ミラーさんの奥さんは親切で優しい人です。',
    translation: 'Vợ của anh Miller là người tốt bụng và dịu dàng.',
    options: ['奥さん', '妻', '家内', '夫'],
    correctIndex: 0,
    explanation: '「奥さん」（おくさん） là cách gọi vợ của người khác một cách tôn trọng.'
  },
  {
    id: 'cloze_minna_9_32',
    vocabId: 'minna_9_32',
    targetWord: '妻',
    targetReading: 'つま',
    sentence: '私の（　　）は高校の先生です。',
    fullSentence: '私の妻は高校の先生です。',
    translation: 'Vợ tôi là giáo viên trường trung học phổ thông.',
    options: ['妻', '奥さん', 'ご主人', '子ども'],
    correctIndex: 0,
    explanation: '「妻」（つま） hoặc 「家内」 là từ khiêm nhường dùng để nói về vợ của chính mình.'
  },
  {
    id: 'cloze_minna_9_33',
    vocabId: 'minna_9_33',
    targetWord: '子ども',
    targetReading: 'こども',
    sentence: '公園で大勢の（　　）が遊んでいます。',
    fullSentence: '公園で大勢の子どもが遊んでいます。',
    translation: 'Nhiều trẻ em đang vui chơi trong công viên.',
    options: ['子ども', '大人', 'ご主人', '奥さん'],
    correctIndex: 0,
    explanation: '「子ども」（こども） nghĩa là con cái, trẻ em.'
  },
  {
    id: 'cloze_minna_9_34',
    vocabId: 'minna_9_34',
    targetWord: 'よく',
    targetReading: 'よく',
    sentence: '日本語が（　　）わかります。',
    fullSentence: '日本語がよくわかります。',
    translation: 'Tôi hiểu rất rõ tiếng Nhật.',
    options: ['よく', 'だいたい', '少し', '全然'],
    correctIndex: 0,
    explanation: 'Phó từ 「よく」 biểu thị mức độ nắm bắt rất tốt hoặc tần suất thường xuyên (rất rõ, thường).'
  },
  {
    id: 'cloze_minna_9_35',
    vocabId: 'minna_9_35',
    targetWord: 'だいたい',
    targetReading: 'だいたい',
    sentence: '今日の授業の内容は（　　）わかりました。',
    fullSentence: '今日の授業の内容はだいたいわかりました。',
    translation: 'Nội dung bài học hôm nay tôi đã đại khái hiểu được.',
    options: ['だいたい', '全然', 'あまり', 'たくさん'],
    correctIndex: 0,
    explanation: 'Phó từ 「だいたい」 nghĩa là đại khái, phần lớn.'
  },
  {
    id: 'cloze_minna_9_36',
    vocabId: 'minna_9_36',
    targetWord: 'たくさん',
    targetReading: 'たくさん',
    sentence: '庭に花が（　　）咲いています。',
    fullSentence: '庭に花がたくさん咲いています。',
    translation: 'Trong vườn có rất nhiều hoa đang nở.',
    options: ['たくさん', '少し', '全然', 'だいたい'],
    correctIndex: 0,
    explanation: '「たくさん」 chỉ số lượng hoặc mức độ nhiều.'
  },
  {
    id: 'cloze_minna_9_37',
    vocabId: 'minna_9_37',
    targetWord: '少し',
    targetReading: 'すこし',
    sentence: '日本語が（　　）話せます。',
    fullSentence: '日本語が少し話せます。',
    translation: 'Tôi có thể nói được một chút tiếng Nhật.',
    options: ['少し', 'たくさん', '全然', 'よく'],
    correctIndex: 0,
    explanation: '「少し」（すこし） nghĩa là một chút, một ít.'
  },
  {
    id: 'cloze_minna_9_38',
    vocabId: 'minna_9_38',
    targetWord: '全然',
    targetReading: 'ぜんぜん',
    sentence: 'フランス語が（　　）わかりません。',
    fullSentence: 'フランス語が全然わかりません。',
    translation: 'Tôi hoàn toàn không hiểu tiếng Pháp.',
    options: ['全然', 'よく', 'たくさん', 'だいたい'],
    correctIndex: 0,
    explanation: '「全然」（ぜんぜん） đi với câu phủ định mang nghĩa là hoàn toàn không...'
  },
  {
    id: 'cloze_minna_9_39',
    vocabId: 'minna_9_39',
    targetWord: '早く',
    targetReading: 'はやく',
    sentence: '明日は試験がありますから、（　　）起きます。',
    fullSentence: '明日は試験がありますから、早く起きます。',
    translation: 'Vì ngày mai có bài thi nên tôi sẽ dậy sớm.',
    options: ['早く', '遅く', 'よく', '少し'],
    correctIndex: 0,
    explanation: '「早く」（はやく） nghĩa là sớm (về mặt thời gian).'
  },
  {
    id: 'cloze_minna_9_40',
    vocabId: 'minna_9_40',
    targetWord: 'から',
    targetReading: 'から',
    sentence: '時間がありません（　　）、タクシーで行きます。',
    fullSentence: '時間がありませんから、タクシーで行きます。',
    translation: 'Vì không có thời gian nên tôi sẽ đi bằng taxi.',
    options: ['から', 'まで', 'が', 'と'],
    correctIndex: 0,
    explanation: 'Liên từ nối 「から」 đứng sau mệnh đề chỉ lý do, nguyên nhân (bởi vì... nên).'
  },
  {
    id: 'cloze_minna_9_41',
    vocabId: 'minna_9_41',
    targetWord: 'どうして',
    targetReading: 'どうして',
    sentence: '（　　）昨日学校を休みましたか。…熱がありましたから。',
    fullSentence: 'どうして昨日学校を休みましたか。…熱がありましたから。',
    translation: 'Tại sao hôm qua bạn lại nghỉ học? ...Vì tôi bị sốt.',
    options: ['どうして', 'どう', 'どこ', 'だれ'],
    correctIndex: 0,
    explanation: 'Nghi vấn từ 「どうして」 dùng để hỏi lý do, nguyên nhân (tại sao).'
  },
  {
    id: 'cloze_minna_9_42',
    vocabId: 'minna_9_42',
    targetWord: 'ざんねんですね',
    targetReading: 'ざんねんですね',
    sentence: '一緒に行けませんか。（　　）。また今度誘ってください。',
    fullSentence: '一緒に行けませんか。ざんねんですね。また今度誘ってください。',
    translation: 'Không thể đi cùng được à? Thật đáng tiếc nhỉ. Lần tới hãy rủ tôi nhé.',
    options: ['ざんねんですね', 'いいですね', 'おめでとうございます', 'ごちそうさまでした'],
    correctIndex: 0,
    explanation: '「ざんねんですね」 dùng để bày tỏ sự tiếc nuối khi không thể tham gia hoặc lỡ mất cơ hội.'
  },
  {
    id: 'cloze_minna_9_43',
    vocabId: 'minna_9_43',
    targetWord: 'すみません',
    targetReading: 'すみません',
    sentence: '（　　）、駅はどちらですか。',
    fullSentence: 'すみません、駅はどちらですか。',
    translation: 'Xin lỗi, nhà ga ở hướng nào ạ?',
    options: ['すみません', 'こんにちは', 'どういたしまして', 'さようなら'],
    correctIndex: 0,
    explanation: '「すみません」 dùng để mở lời xin lỗi hoặc gọi/hỏi người lạ một cách lịch sự.'
  },
  {
    id: 'cloze_minna_9_44',
    vocabId: 'minna_9_44',
    targetWord: 'もしもし',
    targetReading: 'もしもし',
    sentence: '（　　）、ミラーさんはいらっしゃいますか。',
    fullSentence: 'もしもし、ミラーさんはいらっしゃいますか。',
    translation: 'A lô, cho tôi hỏi có anh Miller ở đó không ạ?',
    options: ['もしもし', 'はいどうぞ', 'いらっしゃいませ', '失礼します'],
    correctIndex: 0,
    explanation: '「もしもし」 là câu chào mở đầu quen thuộc khi nghe hoặc gọi điện thoại (A lô).'
  }
];
